### ISSUE TITLE
Ajouter un fichier icalendar du programme?

### ISSUE THREAD

**Issue by sblondon** [AFPy/pyconfr_2017#7]
Je n'ai pas vu de fichiers ical ou pentabarf dans les versions précédentes du site.

S'il y en avait un, cela permettrait aux visiteurs d'avoir le programme de la conférence sur leur ordinateur ou téléphone portable de manière pratique (par exemple avec Giggity sur Android).

J'ai vu que Pelican propose un plugin pour produire un fichier au format ical (https://github.com/getpelican/pelican-plugins/tree/master/events). Par contre, je ne vois pas comment factoriser les données entre le fichier .ics et la version html.

Intéressé par l'idée d'ajouter une fichier .ics au site?

**Comment by lporcheron** [comment]
Hello !
Nous gérons le planning avec PonyConf (github.com/toulibre/ponyconf) qui sort aujourd'hui un format XML du programme. Nous avions créé un bout de js l'année dernière au Capitole du Libre pour transformer dynamiquement le XML en HTML.
On peut je pense étendre PonyConf pour lui faire générer un icalendar :)

Bon, déjà faut qu'on finalise le programme ;-)

**Comment by sblondon** [comment]
PonyConf peut déjà produire le programme au format ics:
```python
planning.views.program(request, output='ics')
```

devrait fonctionner puisque Programme possède une méthode ```is_ics()```.

https://github.com/toulibre/PonyConf/blob/8582f68c774695d977d308f97ad3960af0d2a673/planning/utils.py

(La sortie XML est peut-être suffisante pour certains outils?)

**Comment by sblondon** [comment]
Le programme au format ics sur le ponyconf est accessible à l'adresse suivante:
https://cfp.pycon.fr/schedule/ics

(En regardant le code de ponyconf, j'ai l'impression que l'URL devrait être https://cfp.pycon.fr/schedule/public/?format=ics mais peut-être qu'il y a des modifications sur le serveur? C'est la même situation pour la sortie XML qui est utilisée par pycon.fr_2017.)

J'ai testé Giggity avec l'URL https://cfp.pycon.fr/schedule/ics et cela fonctionne correctement. :-)

 - Si vous voulez que le lien fourni aux visiteurs soit sur www.pycon.fr/2017 plutôt que sur cfp.pycon.fr, il faut rajouter un peu de code ou de configuration sur le serveur web (ProxyPass avec Apache2).
 - Ensuite, on pourrait ajouter un paragraphe expliquant aux utilisateurs comment l'utiliser. Il est pratique de fournir un QrCode contenant l'URL du fichier .ics pour ce que soit flashable par une application mobile. Du coup, cette étape n'est faisable qu'après avoir pris une décision sur l'URL à fournir.

Je peux faire des pull-requests mais il faut que j'ai une idée de la direction à prendre.

**Comment by mmuman** [comment]
Hello,
je viens de faire une PR pour Giggity : https://github.com/Wilm0r/giggity/pull/24

Si possible il faudrait une image carrée plus petite et transparente pour l'icône au lieu du logo.

**Comment by mmuman** [comment]
Par contre je n'arrive pas à charger le programme xml dans Giggity directement à cause de SSL sur mon antique Android 4...

**Comment by sblondon** [comment]
@mmuman j'ai vérifié l'ajout du programme avec le programme XML. ça fonctionne correctement sur Android 7.

**Comment by mmuman** [comment]
Oui c'est probablement parce qu'il ne supporte que des chiffrements obsolètes et donc désactivés.

**Comment by sblondon** [comment]
The icon is available at https://www.pycon.fr/2017/theme/images/icon2017.png.

**Comment by sblondon** [comment]
C'est visible en production donc je clôture cette demande.

**Comment by Alphare** [comment]
Hi,
Le fichier .ics n'est pas importable dans Google Calendar. J'ai essayé sur l'interface web et sur Android, rien n'y fait. En passant le fichier dans un validateur, il ressort des warnings et deux erreurs (répétées pour chaque entrée) : 

> Missing DTSTAMP property near line # 8
> Reference: RFC 5545 3.6.1. Event Component

> Invalid STATUS value near line # 8
> Reference: 3.8.1.11. Status

Je regarderai si j'ai le temps pour faire une PR si je trouve une solution rapide.

**Comment by lporcheron** [comment]
Le fichier ics est généré par PonyConf, donc il va falloir fixer le bug côté PonyConf (coucou @bouttier )

**Comment by bouttier** [comment]
En effet il y a déjà une issue ouvert sur PonyConf : https://github.com/toulibre/PonyConf/issues/72
On va essayer de s’en occuper relativement rapidement du coup.

**Comment by nim65s** [comment]
m’en occupe dans la soirée :)

**Comment by nim65s** [comment]
Plus d’erreurs ni de warnings de https://icalendar.org/validator.html sur https://cfp.pycon.fr.ponyconf.io/staff/schedule/ics/ ; mais google calendar veut toujours pas l’importer, je sais pas pourquoi :/

**Comment by nim65s** [comment]
Ok, c’est valide sur: 
- http://severinghaus.org/projects/icv/
- https://icalendar.org/validator.html
- google calendar
- khal
- nextcloud
- thunderbird

Y’a de temps en temps quelques entités html qui trainent quand même.

**Comment by nim65s** [comment]
Après une mise en prod, il reste un problème sur le mime-type, mais ça a l’air de marcher quand même (et je rajoute vdirsyncer à la liste des trucs testés)

**Comment by Alphare** [comment]
Je confirme que l'import marche dans Google Calendar ! Merci pour vos réponses et le fix rapides.

**Comment by nim65s** [comment]
On vire le HTML: https://github.com/toulibre/PonyConf/issues/85
